# Generated by Django 2.0.13 on 2019-04-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
# ORM - 장고가 데이터베이스와 소통하는법 like 번역가 서로 다른 언어와 DB방식을 소통하고 가져오게 해주는 것
# 왜 있을까?? 

# 모델에서 포스트를 가져오고  포스트의 내용을 담앗다
# 글하나하나를 object
# post all 모든 내용들 다 가져온다
# object title, content 와 같은 